package com.alibaba.android.arouter.register.utils

import java.io.Serializable

/**
 * register setting
 * @author billy.qi email: qiyilike@163.com
 * @since 17/3/28 11:48
 */
class ScanSetting : Serializable {
    /**
     * The register code is generated Into this class
     */
    companion object {
        const val PLUGIN_NAME = "com.alibaba.arouter"
        const val GENERATE_TO_CLASS_NAME = "com/alibaba/android/arouter/core/LogisticsCenter"
        /**
         * you know. this is the class file(or entry in jar file) name
         */
        const val GENERATE_TO_CLASS_FILE_NAME = "$GENERATE_TO_CLASS_NAME.class"
        /**
         * The register code is generated Into this method
         */
        const val GENERATE_TO_METHOD_NAME = "loadRouterMap"
        /**
         * The package name of the class generated by the annotationProcessor
         */
        const val ROUTER_CLASS_PACKAGE_NAME = "com/alibaba/android/arouter/routes/"
        /**
         * The package name of the Interfaces
         */
        private const val INTERFACE_PACKAGE_NAME = "com/alibaba/android/arouter/facade/template/"
        /**
         * register method name in class: {@link #GENERATE_TO_CLASS_NAME}
         */
        const val REGISTER_METHOD_NAME = "register"
    }

    /**
     * scan for classes which : this Interface
     */
    var interfaceName = ""

    /**
     * jar file which contains class: {@link #GENERATE_TO_CLASS_NAME}
     */
    var fileContainsInitClass: java.io.File? = null

    /**
     * scan result for {@link #InterfaceName}
     * class names in this list
     */
    val classList = ArrayList<String>()

    /**
     * constructor for arouter-auto-register settings
     * @param InterfaceName Interface to scan
     */
    constructor(_interfaceName: String) : this() {
        this.interfaceName = INTERFACE_PACKAGE_NAME + _interfaceName
    }
    
    constructor() : super()
}